import { useEffect, useRef, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import confetti from "canvas-confetti";
import api from "../api/client.js";
import { computeLeaderboard } from "../utils/scoring.js";
import GlassCard from "../components/ui/GlassCard.jsx";
import Podium from "../components/Podium.jsx";
import Scoreboard from "../components/Scoreboard.jsx";
import CompactPlayerCard from "../components/ui/CompactPlayerCard.jsx";
import useOlympicStore from "../store/useOlympicStore.js";
import { Trophy, Rocket, Home, ClipboardList, Check, ChevronUp, ChevronDown, Sparkles } from "lucide-react";
import { AVATAR_GRADIENTS } from "../components/Header.jsx";

export default function WinnerPage() {
  const { code } = useParams();
  const navigate = useNavigate();
  const { olympic: storeOlympic, leaderboard: storeLeaderboard } =
    useOlympicStore();

  const [olympic, setOlympic] = useState(storeOlympic);
  // Prefer finalLeaderboard snapshot from store if available
  const [leaderboard, setLeaderboard] = useState(
    storeOlympic &&
      Array.isArray(storeOlympic.finalLeaderboard) &&
      storeOlympic.finalLeaderboard.length > 0
      ? storeOlympic.finalLeaderboard
      : storeLeaderboard,
  );
  const [loading, setLoading] = useState(!storeOlympic);
  const [copied, setCopied] = useState(false);
  const [showBonusLog, setShowBonusLog] = useState(false);

  const confettiFired = useRef(false);

  // Clear any active room from localStorage — the game is over
  useEffect(() => {
    localStorage.removeItem("lastRoom");
  }, []);

  // Fetch from API if not in store
  useEffect(() => {
    if (!storeOlympic && code) {
      api
        .get(`/olympics/${code.toUpperCase()}`)
        .then(({ data }) => {
          setOlympic(data);
          // Use persisted finalLeaderboard if available, otherwise compute
          setLeaderboard(
            Array.isArray(data.finalLeaderboard) &&
              data.finalLeaderboard.length > 0
              ? data.finalLeaderboard
              : computeLeaderboard(data),
          );
        })
        .catch(() => navigate("/"))
        .finally(() => setLoading(false));
    }
  }, [code]);

  // Fire confetti on mount
  useEffect(() => {
    if (!confettiFired.current && leaderboard.length > 0) {
      confettiFired.current = true;
      const duration = 3000;
      const end = Date.now() + duration;

      const frame = () => {
        confetti({
          particleCount: 5,
          angle: 60,
          spread: 55,
          origin: { x: 0 },
          colors: ["#8b5cf6", "#ec4899", "#22d3ee", "#facc15"],
        });
        confetti({
          particleCount: 5,
          angle: 120,
          spread: 55,
          origin: { x: 1 },
          colors: ["#8b5cf6", "#ec4899", "#22d3ee", "#facc15"],
        });
        if (Date.now() < end) requestAnimationFrame(frame);
      };
      frame();
    }
  }, [leaderboard]);

  function copyResults() {
    const winner = leaderboard[0];
    const text = [
      `🏅 ${olympic?.name} — Final Results`,
      "",
      ...leaderboard.map(
        (p, i) =>
          `${["🥇", "🥈", "🥉"][i] || `${i + 1}.`} ${p.name} — ${p.total} pts (${p.wins} wins)`,
      ),
      "",
      `Generated by Party Olympiade`,
    ].join("\n");

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-muted animate-pulse">Loading results…</div>
      </div>
    );
  }

  if (!olympic) return null;

  const scoringEnabled = olympic.scoringEnabled !== false;
  const winner = leaderboard[0];
  const allBonusLogs = leaderboard.flatMap((p) =>
    (p.bonusLog || []).map((log) => ({ player: p.name, ...log })),
  );

  // No-score view
  if (!scoringEnabled) {
    return (
      <div className="min-h-screen px-4 py-10">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center animate-fade-in">
            <h1 className="text-4xl sm:text-5xl font-black text-white mb-2 flex items-center justify-center gap-3">
              <Sparkles className="text-pink-400" size={40} />
              Event Complete!
            </h1>
            <p className="text-muted">{olympic.name}</p>
          </div>

          <GlassCard>
            <h2 className="font-bold text-white mb-4">
              Participants ({olympic.participants.length})
            </h2>
            <div className="space-y-2">
              {olympic.participants.map((p) => (
                <div
                  key={p.name}
                  className="flex items-center gap-3 py-2 border-b border-white/5"
                >
                  {p.avatarBase64 ? (
                    <img
                      src={p.avatarBase64}
                      alt={p.name}
                      className="w-10 h-10 rounded-full object-cover"
                    />
                  ) : (
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple to-pink flex items-center justify-center font-bold text-white">
                      {p.name[0]}
                    </div>
                  )}
                  <span className="font-medium text-white">{p.name}</span>
                </div>
              ))}
            </div>
          </GlassCard>

          <div className="flex flex-col sm:flex-row gap-3 pb-8">
            <button
              className="btn-primary flex-1 flex items-center justify-center gap-2"
              onClick={() => navigate("/create")}
            >
              <Rocket size={15} /> New Olympic
            </button>
            <button className="btn-ghost flex-1 flex items-center justify-center gap-2" onClick={() => navigate("/")}>
              <Home size={15} /> Home
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen px-4 py-10">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Hero */}
        <div className="text-center animate-fade-in">
          <h1 className="text-4xl sm:text-5xl font-black text-white mb-2 flex items-center justify-center gap-3">
            <Trophy className="text-yellow-400" size={40} />
            Olympic Champion!
          </h1>
          <p className="text-muted">{olympic.name}</p>
        </div>

        {/* Winner highlight */}
        {winner && (() => {
          const winnerParticipant = olympic.participants.find((p) => p.name === winner.name);
          const avatarGrad = winnerParticipant?.avatarColor != null
            ? AVATAR_GRADIENTS[winnerParticipant.avatarColor] ?? AVATAR_GRADIENTS[0]
            : "linear-gradient(135deg, #eab308, #f97316)";
          return (
            <div
              className="glass rounded-2xl p-6 text-center shadow-[0_0_40px_rgba(139,92,246,0.15)]"
              style={{
                background:
                  "linear-gradient(135deg, rgba(250,204,21,0.12), rgba(245,158,11,0.06)), linear-gradient(138deg, rgba(18,18,36,0.85), rgba(28,28,56,0.6))",
              }}
            >
              {/* Winner card art */}
              <div className="flex justify-center mb-4">
                <div style={{ background: avatarGrad, padding: "2px", borderRadius: 18, boxShadow: "0 0 60px rgba(250,204,21,0.35)" }}>
                  <div style={{ width: 96, height: 96, borderRadius: 17, overflow: "hidden", background: winnerParticipant?.cardImage ? "transparent" : avatarGrad, position: "relative", display: "flex", alignItems: "center", justifyContent: "center" }}>
                    {winnerParticipant?.cardImage ? (
                      <img src={winnerParticipant.cardImage} alt="" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" }} />
                    ) : (
                      <>
                        <div style={{ position: "absolute", inset: 0, background: "linear-gradient(180deg,rgba(5,3,15,0.3),rgba(5,3,15,0.5))" }} />
                        <span style={{ position: "relative", zIndex: 1, fontSize: 40, fontWeight: 900, color: "white", textShadow: "0 2px 12px rgba(0,0,0,0.5)" }}>
                          {winner.name[0]?.toUpperCase()}
                        </span>
                      </>
                    )}
                  </div>
                </div>
              </div>
              <h2 className="text-3xl font-black text-yellow-400 mb-1">
                {winner.name}
              </h2>
              <p className="text-white font-bold">
                {winner.total} points · {winner.wins} wins
              </p>
            </div>
          );
        })()}

        {/* Podium */}
        <div className="pt-4">
          <Podium
            leaderboard={leaderboard}
            participants={olympic.participants}
          />
        </div>

        {/* Player cards */}
        {olympic.participants.length > 0 && (
          <GlassCard>
            <h2 className="font-bold text-white mb-4">Spieler</h2>
            <div className="flex flex-wrap gap-3 justify-center">
              {leaderboard.map((entry, i) => {
                const p = olympic.participants.find((pt) => pt.name === entry.name);
                return (
                  <CompactPlayerCard
                    key={entry.name}
                    name={entry.name}
                    avatarColor={p?.avatarColor ?? null}
                    cardImage={p?.cardImage ?? null}
                    playerCard={p?.playerCard ?? null}
                    fallbackIndex={i}
                  />
                );
              })}
            </div>
          </GlassCard>
        )}

        {/* Full leaderboard */}
        <GlassCard>
          <h2 className="font-bold text-white mb-4">Final Standings</h2>
          <Scoreboard
            leaderboard={leaderboard}
            participants={olympic.participants}
          />
        </GlassCard>

        {/* Bonus log */}
        {allBonusLogs.length > 0 && (
          <GlassCard>
            <button
              className="flex items-center justify-between w-full"
              onClick={() => setShowBonusLog((s) => !s)}
            >
              <h2 className="font-bold text-white">Bonus / Penalty Log</h2>
              <span className="text-muted text-sm">
                {showBonusLog ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </span>
            </button>
            {showBonusLog && (
              <div className="mt-3 space-y-1.5">
                {allBonusLogs.map((log, i) => (
                  <div
                    key={i}
                    className="flex items-center gap-2 text-sm py-1.5 border-b border-white/5"
                  >
                    <span className="font-medium text-white w-24 truncate">
                      {log.player}
                    </span>
                    <span className="text-muted flex-1">
                      {log.game} — {log.reason}
                    </span>
                    <span
                      className={`font-bold ${log.delta > 0 ? "text-green-400" : "text-pink-400"}`}
                    >
                      {log.delta > 0 ? `+${log.delta}` : log.delta}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </GlassCard>
        )}

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-3 pb-8">
          <button className="btn-primary flex-1 flex items-center justify-center gap-2" onClick={copyResults}>
            {copied ? <><Check size={15} /> Copied!</> : <><ClipboardList size={15} /> Copy Results</>}
          </button>
          <button
            className="btn-secondary flex-1 flex items-center justify-center gap-2"
            onClick={() => navigate("/create")}
          >
            <Rocket size={15} /> New Olympic
          </button>
          <button className="btn-ghost flex-1 flex items-center justify-center gap-2" onClick={() => navigate("/")}>
            <Home size={15} /> Home
          </button>
        </div>
      </div>
    </div>
  );
}
